### ISSUE TITLE
Allow a random seed to be set

### ISSUE THREAD

**Issue by tdealtry** [JostMigenda/sntools#10]
For reproducibility, it'd be nice to have the option to set a seed in `genevts.py`

From our discussions, you've noted that you used both `random` and `np.random` So these should both have seeds sets. Whether they're the same, indpendently settable, or have an offset (e.g. `SEED` and `SEED + 10`) I have no opinion on

**Comment by JostMigenda** [comment]
In principle, this can be achieved by adding these four lines at the top of `genevts.py`:
```
import random
import numpy as np
random.seed(12345)
np.random.seed(12345)
```
(For the purposes of sntools, I don’t think it matters much whether or not we use the same seed for both.)

In my preliminary testing, this generates reproducible outputs for a given Python installation—but not necessarily across different installations.

I _think_ this is because some different versions of scipy have slight differences in their numerical integration/interpolation algorithms—and while those are negligible for physics purposes, the slightly different inputs to `np.random.poisson()` in `channel.py` may make it return different event numbers, which kills reproducibility.

I’ll need to figure out in which version(s) of scipy those changes happened and whether there are any other differences between various Python/numpy/scipy versions (and across different operating systems). If it’s just a few old versions of scipy, it’s probably okay not to support them; but if there are more differences and I can’t find a good workaround, would it be useful to have reproducibility only for the same software version? (Might need to write the versions used to the header of the output file in that case …)

**Comment by JostMigenda** [comment]
I think [this is the change in scipy](https://github.com/scipy/scipy/pull/5351) I was looking for.

From scipy 0.17.0 onwards I get consistent results. Will need to do more extensive tests; but if no other issues crop up, this should be pretty straightforward to implement.
